#[cfg(test)]
mod tests {
    use super::super::modules::*;
    #[test]
    fn test_CPU() {
        let mut m = CPU::new();
        m.instruction = 12345;
        m.prop();
        assert_eq!(m.pc, 0);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 12345);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 0);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 12345);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 12345);
        m.instruction = 60432;
        m.prop();
        assert_eq!(m.pc, 1);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 60432);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 12345);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 2);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 60432);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 12345);
        m.instruction = 23456;
        m.prop();
        assert_eq!(m.pc, 2);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 23456);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 12345);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 3);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 23456);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 23456);
        m.instruction = 57840;
        m.prop();
        assert_eq!(m.pc, 3);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 57840);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 23456);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 4);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 57840);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 11111);
        m.instruction = 1003;
        m.prop();
        assert_eq!(m.pc, 4);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1003);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 11111);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 5);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1003);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1003);
        m.instruction = 58120;
        m.prop();
        assert_eq!(m.pc, 5);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58120);
        assert_eq!(m.outM, 11111);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1003);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 6);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58120);
        assert_eq!(m.outM, 11111);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1003);
        m.instruction = 1004;
        m.prop();
        assert_eq!(m.pc, 6);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1004);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1003);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 7);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1004);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1004);
        m.instruction = 58264;
        m.prop();
        assert_eq!(m.pc, 7);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58264);
        assert_eq!(m.outM, 11110);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1004);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 8);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58264);
        assert_eq!(m.outM, 11109);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1004);
        m.instruction = 1000;
        m.prop();
        assert_eq!(m.pc, 8);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1000);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1004);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 9);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1000);
        assert_eq!(m.inM, 0);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 62704;
        m.inM = 11111;
        m.prop();
        assert_eq!(m.pc, 9);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 62704);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 10);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 62704);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 32767);
        m.instruction = 14;
        m.prop();
        assert_eq!(m.pc, 10);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 14);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 32767);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 11);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 14);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 14);
        m.instruction = 58116;
        m.prop();
        assert_eq!(m.pc, 11);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 14);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 14);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 14);
        m.instruction = 999;
        m.prop();
        assert_eq!(m.pc, 14);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 999);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 14);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 15);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 999);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 999);
        m.instruction = 64992;
        m.prop();
        assert_eq!(m.pc, 15);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64992);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 999);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 16);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64992);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 11112);
        m.instruction = 58152;
        m.prop();
        assert_eq!(m.pc, 16);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58152);
        assert_eq!(m.outM, 65535);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 11112);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 17);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58152);
        assert_eq!(m.outM, 65535);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 32767);
        m.instruction = 21;
        m.prop();
        assert_eq!(m.pc, 17);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 21);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 32767);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 18);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 21);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 21);
        m.instruction = 59330;
        m.prop();
        assert_eq!(m.pc, 18);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 59330);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 21);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 21);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 59330);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 21);
        m.instruction = 2;
        m.prop();
        assert_eq!(m.pc, 21);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 2);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 21);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 22);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 2);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 2);
        m.instruction = 57528;
        m.prop();
        assert_eq!(m.pc, 22);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 57528);
        assert_eq!(m.outM, 1);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 2);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 23);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 57528);
        assert_eq!(m.outM, 2);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1);
        m.instruction = 64968;
        m.prop();
        assert_eq!(m.pc, 23);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64968);
        assert_eq!(m.outM, 11112);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 24);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64968);
        assert_eq!(m.outM, 11112);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1);
        m.instruction = 64680;
        m.prop();
        assert_eq!(m.pc, 24);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64680);
        assert_eq!(m.outM, 11110);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 1);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 25);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 64680);
        assert_eq!(m.outM, 11110);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, true);
        assert_eq!(m.addressM, 11110);
        m.instruction = 1000;
        m.prop();
        assert_eq!(m.pc, 25);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1000);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 11110);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 26);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 1000);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 61072;
        m.prop();
        assert_eq!(m.pc, 26);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 61072);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 27);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 61072);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58113;
        m.prop();
        assert_eq!(m.pc, 27);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 28);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58114;
        m.prop();
        assert_eq!(m.pc, 28);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 29);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58115;
        m.prop();
        assert_eq!(m.pc, 29);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 30);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58116;
        m.prop();
        assert_eq!(m.pc, 30);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58117;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58118;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58119;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 60048;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 60048);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 60048);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58113;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1002);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58114;
        m.prop();
        assert_eq!(m.pc, 1002);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58115;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58116;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58117;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1002);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58118;
        m.prop();
        assert_eq!(m.pc, 1002);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58119;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 61392;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 61392);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 61392);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58113;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58113);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58114;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58114);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58115;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58115);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58116;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58116);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58117;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58117);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58118;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58118);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 58119;
        m.prop();
        assert_eq!(m.pc, 1001);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.reset = true;
        m.prop();
        assert_eq!(m.pc, 1000);
        assert_eq!(m.reset, true);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 0);
        assert_eq!(m.reset, true);
        assert_eq!(m.instruction, 58119);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.instruction = 32767;
        m.reset = false;
        m.prop();
        assert_eq!(m.pc, 0);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 32767);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 1000);
        m.posedge_clk();
        m.prop();
        assert_eq!(m.pc, 1);
        assert_eq!(m.reset, false);
        assert_eq!(m.instruction, 32767);
        assert_eq!(m.inM, 11111);
        assert_eq!(m.writeM, false);
        assert_eq!(m.addressM, 32767);
    }
}
