[workspace]
members = [
    "vm",
    "assembler",
    "rtl",
    "behavior",
    "sim/chapter01",
    "sim/chapter02",
    "sim/chapter03/a",
    "sim/chapter03/b",
    "sim/chapter05",
    "sim/chapter07",
    "tool/hdl2kaze"
]
