#[cfg(test)]
mod tests {
use super::super::modules::*;
#[test]
fn test_RAM64(){
let mut m = RAM64::new();
m.in_ = 0;
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.address, 0);
m.load = true;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.address, 0);
m.in_ = 1313;
m.load = false;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 0);
m.load = true;
m.address = 13;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 13);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 13);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 1313);
assert_eq!(m.address, 0);
m.in_ = 4747;
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.load = true;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.load = false;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 47);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 4747);
assert_eq!(m.address, 13);
m.in_ = 6363;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 13);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 13);
m.load = true;
m.address = 63;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 63);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 6363);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 63);
m.load = false;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 6363);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 63);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 6363);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 63);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 47);
m.address = 63;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 6363);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 63);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 6363);
assert_eq!(m.address, 47);
m.load = true;
m.in_ = 21845;
m.address = 40;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 4747);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.load = true;
m.address = 40;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 40;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.address = 41;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 41;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.address = 42;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 42;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.address = 43;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 43;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.address = 44;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 44;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.address = 45;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 45;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 46;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 46;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.address = 47;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 47);
m.load = true;
m.address = 47;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.load = false;
m.address = 40;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 40);
m.address = 41;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 41);
m.address = 42;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 42);
m.address = 43;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 43);
m.address = 44;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 44);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 46;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 46);
m.address = 47;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 47);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.load = true;
m.in_ = 21845;
m.address = 5;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 1313);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.load = true;
m.address = 5;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 5;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.address = 13;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 13;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.address = 21;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 21;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.address = 29;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 29;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.address = 37;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 37;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.address = 45;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 45;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 53;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 53;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.address = 61;
m.in_ = 43690;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.address, 61);
m.load = true;
m.address = 61;
m.in_ = 21845;
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.posedge_clk();
m.prop();
assert_eq!(m.load, true);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
m.load = false;
m.address = 5;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 5);
m.address = 13;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 13);
m.address = 21;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 21);
m.address = 29;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 29);
m.address = 37;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 37);
m.address = 45;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 45);
m.address = 53;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 53);
m.address = 61;
m.prop();
assert_eq!(m.load, false);
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.address, 61);
}
}
