#[cfg(test)]
mod tests {
use super::super::modules::*;
#[test]
fn test_RAM8(){
let mut m = RAM8::new();
m.in_ = 0;
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.load = true;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 0);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.in_ = 11111;
m.load = false;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.load = true;
m.address = 1;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 11111);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.in_ = 3333;
m.address = 3;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.load = true;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.load = false;
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 1;
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 3333);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.in_ = 7777;
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.load = true;
m.address = 7;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.load = false;
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.address = 3;
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 7;
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 7777);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.in_ = 21845;
m.address = 0;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 11111);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 3333);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 0);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 7777);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 0;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 0;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 0);
m.address = 1;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 1;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 1);
m.address = 2;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 2;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 2);
m.address = 3;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 3;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 3);
m.address = 4;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 4;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 4);
m.address = 5;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 5;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 5);
m.address = 6;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 6;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 6);
m.address = 7;
m.in_ = 43690;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 43690);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
m.load = true;
m.address = 7;
m.in_ = 21845;
m.prop();
assert_eq!(m.out, 43690);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, true);
assert_eq!(m.address, 7);
m.load = false;
m.address = 0;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.posedge_clk();
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 0);
m.address = 1;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 1);
m.address = 2;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 2);
m.address = 3;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 3);
m.address = 4;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 4);
m.address = 5;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 5);
m.address = 6;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 6);
m.address = 7;
m.prop();
assert_eq!(m.out, 21845);
assert_eq!(m.in_, 21845);
assert_eq!(m.load, false);
assert_eq!(m.address, 7);
}
}
